### ISSUE TITLE
[question] How to cite inside a footnote?

### ISSUE THREAD

**Issue by fredguth** [pfasante/phd_thesis#10]
In your example dissertation, the footnote is a sidenote.  When I try to cite inside a footnote, only the footnote mark appears in the rendering. The footnote does not show.  

In the figure caption, I solved a similar problem by adding a \footenotemark and then outside the figure a \footnotetext. 

But here I have no clue.

**Comment by pfasante** [comment]
Maybe thats a problem with the `\sidecite` macro - a work around would be, to use `\citeonly`, to prevent the citation to appear in the side margin.

I understand that this is not ideal, but I did not find out how to make the sidecite implementation more robust - and to be honest, I will also not find out now or later, as I (sadly) do use latex much less nowadays :'(

**Comment by fredguth** [comment]
Ah, now I get what \citeonly is :-D
