### ISSUE TITLE
[bug] End of page citation problem.

### ISSUE THREAD

**Issue by fredguth** [pfasante/phd_thesis#11]
See error in figure: https://share.getcloudapp.com/5zuYekkJ

I have the same author been cited in paragraphs that are near.  The first time he is cited is on one page, and then it should be "sidecited" again in the beginning of the next page. But the citation appears in the previous page, in the wrong margin (or in the correct margin in the wrong height).

How can I help fix this?

**Comment by fredguth** [comment]
Sorry, it is the same matter than before.  The problem is that I added a citation in the footnote.

**Comment by pfasante** [comment]
Do I understand correctly, that you fixed your problem?

I also had problems with `\sidecite` at the bottom of pages and resolved it by either reformulating the text or using `\citeonly`.

(BTW nitpick regarding your footnotes: IIRC you should place them after punctiation marks, i.e. ".\footnote{…}" instead of "\footnote{…}.")

**Comment by pfasante** [comment]
(see also issue #1)

**Comment by fredguth** [comment]
I did not solve. It still happens. Thanks for nitpicking :-)

\citeonly is a command or is it \cite only?
All may footnotes are now \sidenotes (copied from your dissertation).  Maybe I should differentiate them and use create a proper footnote for these cases.

**Comment by pfasante** [comment]
Did you found a solution for your problem @fredguth?

**Comment by fredguth** [comment]
I changed to \citeonly. I had several of these small errors.  
Two of my chapters have lost text errors and I have to press enter for pdflatex to finish compiling. 
I am considering adding the option of space in the citation in the marginpar.
