### ISSUE TITLE
Full page width figures

### ISSUE THREAD

**Issue by cassianorabelo** [pfasante/phd_thesis#3]
Turon's thesis (as well as Tufte's LaTeX template) has full page width figures like the one below (fig. 5.6). 

<img width="624" alt="Screen Shot 2019-08-14 at 17 52 15" src="https://user-images.githubusercontent.com/65070/63058132-54f84380-bec2-11e9-8f0f-3ac4e82b2e83.png">

I tried a few different ways to achieve that, but didn't succeed. 
Is this possible? Could you help with that?
Thanks.

**Comment by pfasante** [comment]
You can set the figures in a `fullwidth` environment, but the sidecaption as in the figure will not work currently I think. An example table set in fullwidth is [this](https://github.com/pfasante/phd_thesis/blob/55160b93594fc0cf34b7cf5e8312f7f581c2b830/mainmatter/slps.tex#L435).

**Comment by cassianorabelo** [comment]
I just made a pull request with a proposed fix for this (pull request #4 )

**Comment by pfasante** [comment]
Fixed by #4
