### ISSUE TITLE
side citation not matching main text citation style

### ISSUE THREAD

**Issue by cassianorabelo** [pfasante/phd_thesis#5]
If I change the citation style to "numeric", the citations on the margin use a different (fixed) style. I've been trying to make one match the other manually, but wasn't able to.
I believe I have to change the "\newbibmacro{sidecite}" macro, but I don't know how.

Could you help me with that? I'm not talking about a way to automatically match both, only where to change to make them match manually.
Thanks!

![image](https://user-images.githubusercontent.com/65070/63265721-a149d780-c264-11e9-9213-6c2d4d6df344.png)

**Comment by pfasante** [comment]
Something like this should work:

```
diff --git a/dissertation.cls b/dissertation.cls
index 67408da..83fb731 100644
--- a/dissertation.cls
+++ b/dissertation.cls
@@ -122,7 +122,6 @@
 %     \caption{Caption for a full-width figure appearing in the margin
 %       below it.}}
 % \end{figure}
-
 \pagestyle{diss}
 %%% Part Style %%%
@@ -276,7 +275,7 @@
     maxbibnames=20,
     maxcitenames=2,
     %giveninits=true,
-    style=alphabetic,
+    style=numeric,
     sorting=nyt,
     sortcites=false,
     citetracker=true,
@@ -351,10 +350,7 @@
   \marginpar{%
     \toggletrue{blx@footnote}%
     \footnotesize%
-    \printtext[labelalphawidth]{%
-      \printfield{labelprefix}%
-      \printfield{labelalpha}%
-      \printfield{extraalpha}}
+    \printfield[labelnumberwidth]{labelnumber}
     \setunit{\addnbspace}%
     \printnames{labelname}%
     \setunit{\printdelim{nametitledelim}}%
```

**Comment by cassianorabelo** [comment]
Worked like a charm. Thank you.
It gives an error if I try to use "style=numeric-comp", but that is not really necessary.
