### ISSUE TITLE
Main body font-size

### ISSUE THREAD

**Issue by cassianorabelo** [pfasante/phd_thesis#7]
Hello Friedrich,
sorry for using the issue to ask this question... I don't have other means to contact you.
I was trying to increase the font-size of the main body text, but it started to break things. I believe I'm doing it wrong. Do you mind pointing me to the proper way of doing that? What about the text in the caption of the figures? Thank you.

**Comment by pfasante** [comment]
you can find my contact details on my GitHub page: https://pfasante.github.io/ -- but maybe it's not to bad to have this as a kind of "documentation" ;)

There are some places where the font size is set in the .cls file.:
l. 10 in the LoadClass options
l. 13-15 with the fontsize macro

Most probably you then also want to adjust the layout/margins.
l. 32-42 are for the normal page layout and in the following, you then also have to adjust the header & footer styles.

The caption style is set with the caption package, so l. 232 is maybe what you are looking for?

**Comment by cassianorabelo** [comment]
First of all, 
thank you for all the help.

> you can find my contact details on my GitHub page: https://pfasante.github.io/ -- but maybe it's not to bad to have this as a kind of "documentation" ;)

To be honest, I felt bad about sending you an email... too invasive. Since my question was, in a way, related to this project, I decided to post here. There is a wiki feature here on github, but I think you disabled it or it is disabled by default. If you turn it on, I could try to put a few things in there.

> There are some places where the font size is set in the .cls file.:
> l. 10 in the LoadClass options

When changing that, from 10pt to 12pt, for example, only the headers and other parts change. The body text stays the same. That's what caught me.

> l. 13-15 with the fontsize macro

Somehow even after changing these lines, my main text still didn't change. After your confirmation that this is the way to do it, I found out that I had accidentally overwritten this on my diss.tex. My bad! :)

As a final question, how is your building workflow? Mine is taking ages to compile...

Thanks a lot!

**Comment by pfasante** [comment]
I created a first wiki page, can you add new ones now? I did not disabled anything wiki related on purpose, but also have never used this feature before..

Glad that it helped you, so I'll close the issue now.

The workflow well.. is slow on my machine, too :D I felt like spending half of my writing-time on compiling the thesis.. You can, of course, speed the process up a bit by uncommenting most of the thesis and things like this, but I found this not really convincing. So not sure if this could be solved somehow..
