### ISSUE TITLE
Minitoc per chapter

### ISSUE THREAD

**Issue by Chutlhu** [pfasante/phd_thesis#8]
Hi! Thank you very much for this template. It is amazing.
I am trying to add a mini table of content at the beginning of each chapter. 
I tried with \minitoc, but I experience error.
Do you know how to do it easily?
Thank you very much

**Comment by pfasante** [comment]
Glad that you like it and that it is helpful :)

I've never used `\minitoc` so cannot tell you instantely. Maybe I can help, if you give more details on what goes wrong etc. A minimal working example would also help to understand the error.

**Comment by Chutlhu** [comment]
Hi,
I manage to solve the issues with minitoc. There was nothing wrong with the template. 
This problem arised because of the usage of starred chapter:
I solved by using:
\setcounter{mtc}{9}

more details in
https://latex.org/forum/viewtopic.php?t=26066
https://tex.stackexchange.com/questions/315702/minitoc-problem

**Comment by pfasante** [comment]
Good to know, thanks for reporting!
