### ISSUE TITLE
[question] How to change the top margin?

### ISSUE THREAD

**Issue by fredguth** [pfasante/phd_thesis#9]
I have been trying to make some tweaks to better resemble Turon's thesis.  I think the top margin is a little bigger (maybe 1cm bigger, even more in ToC).

I have tried:
```
\setlength{\topmargin}{50mm}% exaggerated
\setlength{\headheight}{50mm}% exaggerated
```

Also, tried changing the textheight
```
\newenvironment{fullwidth}{%
    \newgeometry{
      inner=26mm,
      outer=26mm,
      textheight=200mm}
    \aliaspagestyle{chapter}{fullwidthplain}
    \pagestyle{fullwidth}
}{%
    \restoregeometry
}
```
and textheight and top
```
\newenvironment{fullwidth}{%
    \newgeometry{
      inner=26mm,
      outer=26mm,
      top = 50mm,
      textheight=200mm}
    \aliaspagestyle{chapter}{fullwidthplain}
    \pagestyle{fullwidth}
}{%
    \restoregeometry
}
```

**Comment by pfasante** [comment]
I think the right way is via the `\setmarginsandblock` macro (see https://tex.stackexchange.com/questions/154406/increase-textblock-size-in-memoir-document) in https://github.com/pfasante/phd_thesis/blob/c659e43a02b295e356700636b200c32d37058c67/dissertation.cls#L32 until https://github.com/pfasante/phd_thesis/blob/c659e43a02b295e356700636b200c32d37058c67/dissertation.cls#L41.

But as I do not have the repository set up on my current machine, I cannot experiment. Checking the memoir handbook might also be very helpful, it has quite some details.
I can also check, if I find some time, but no guarantees :)
